name: Discord Notification Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize]
                
jobs:
  success:
    name: Successful deployment
    runs-on: ubuntu-latest
    steps:
      - uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: A deployment was made and it has been observed as successful.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  failure:
    name: Failed deployment
    runs-on: ubuntu-latest
    steps:
      - uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          details: Deployment Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  cancelled:
    name: Cancelled deployment
    runs-on: ubuntu-latest
    steps:
      - uses: rjstone/discord-webhook-notify@v1.0.4
        if: cancelled()
        with:
          severity: warning
          details: Deployment Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}