name: Fly Deploy
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  SKIP: ${{ contains(join(github.event.commits.message, ' '), '#skip') }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    if: ${{ github.event_name == 'push' && github.env.SKIP == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    if: ${{ github.env.SKIP == 'false' }}
    needs: [deploy]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.70.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true
        DEFAULT_BUMP: patch

